FROM php:7-apache
MAINTAINER tshinow <shinohara@n-di.co.jp>

RUN usermod -u 1000 www-data \
  && groupmod -g 1000 www-data

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libmagickwand-dev \
        imagemagick \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng12-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i "s/\/var\/www\/html/\/var\/www\/html\/laravel\/public/g" /etc/apache2/sites-available/000-default.conf
RUN sed -i "s/\/var\/www/\/var\/www\/html\/laravel/g" /etc/apache2/apache2.conf
RUN sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf

RUN a2enmod rewrite

RUN apt-get update \
    && apt-get install -y \
        curl \
        cron \
        g++ \
        git \
        gcc \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxml2-dev \
        libxslt1-dev \
        make \
        mc \
        supervisor \
        tar \
        unzip \
        vim \
        wget

RUN docker-php-ext-configure \
    gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

RUN pecl install xdebug \

RUN echo "[Date]" > /usr/local/etc/php/conf.d/date.ini \
  && echo "date.timezone=Asia/Tokyo" >> /usr/local/etc/php/conf.d/date.ini \
  && echo "upload_max_filesize = 20M" > /usr/local/etc/php/conf.d/upload.ini \
  && echo "post_max_size = 20M" >> /usr/local/etc/php/conf.d/upload.ini

EXPOSE 80
CMD ["apache2-foreground"]
